import path from 'path';
import fs from 'fs-extra';
import chalk from 'chalk';
import ora from 'ora';
import { select } from '@inquirer/prompts';
import { AI_KIT_CONFIG_FILE, GENERATED_FILES } from '../constants.js';
import {
  logSection,
  logInfo,
  logSuccess,
  logWarning,
  logError,
  fileExists,
  readJsonSafe,
  readFileSafe,
} from '../utils.js';
import type { AiKitConfig } from '../types.js';

type ExportFormat = 'windsurf' | 'aider' | 'cline' | 'all';

const EXPORT_TARGETS = {
  windsurf: { file: '.windsurfrules', label: 'Windsurf' },
  aider: { file: '.aider.conf.yml', label: 'Aider' },
  cline: { file: '.clinerules', label: 'Cline' },
} as const;

function stripMarkers(content: string): string {
  return content
    .replace('<!-- AI-KIT:START -->\n', '')
    .replace('\n<!-- AI-KIT:END -->', '')
    .replace(/<!-- Generated by ai-kit v[\d.]+ -->\n?/, '');
}

function toWindsurf(content: string): string {
  const stripped = stripMarkers(content);
  return `# Windsurf Rules\n# Exported from ai-kit CLAUDE.md\n\n${stripped}`;
}

function toAider(content: string): string {
  const stripped = stripMarkers(content);
  // Indent each line for YAML multiline block scalar
  const indented = stripped
    .split('\n')
    .map((line) => (line.length > 0 ? `  ${line}` : ''))
    .join('\n');
  return `# Aider configuration\n# Exported from ai-kit CLAUDE.md\n\nconventions: |\n${indented}\n`;
}

function toCline(content: string): string {
  const stripped = stripMarkers(content);
  return `# Cline Rules\n# Exported from ai-kit CLAUDE.md\n\n${stripped}`;
}

export async function exportCommand(
  targetPath?: string,
  options?: { format?: string },
): Promise<void> {
  const projectDir = path.resolve(targetPath || process.cwd());
  const configPath = path.join(projectDir, AI_KIT_CONFIG_FILE);
  const claudeMdPath = path.join(projectDir, GENERATED_FILES.claudeMd);

  logSection('AI Kit — Export');

  // Check that ai-kit has been initialized
  if (!fileExists(configPath) && !fileExists(claudeMdPath)) {
    logError('No ai-kit.config.json or CLAUDE.md found. Run `ai-kit init` first.');
    return;
  }

  // Read CLAUDE.md content
  const claudeContent = readFileSafe(claudeMdPath);
  if (!claudeContent) {
    logError('Could not read CLAUDE.md. Run `ai-kit init` or `ai-kit update` first.');
    return;
  }

  // Determine format
  let format: ExportFormat;

  if (options?.format) {
    const f = options.format.toLowerCase();
    if (f === 'windsurf' || f === 'aider' || f === 'cline' || f === 'all') {
      format = f;
    } else {
      logError(`Unknown format "${options.format}". Use: windsurf, aider, cline, or all.`);
      return;
    }
  } else {
    format = await select<ExportFormat>({
      message: 'Which format do you want to export to?',
      choices: [
        { name: 'Windsurf (.windsurfrules)', value: 'windsurf' },
        { name: 'Aider (.aider.conf.yml)', value: 'aider' },
        { name: 'Cline (.clinerules)', value: 'cline' },
        { name: 'All of the above', value: 'all' },
      ],
    });
  }

  const formats: (keyof typeof EXPORT_TARGETS)[] =
    format === 'all' ? ['windsurf', 'aider', 'cline'] : [format];

  const spinner = ora('Exporting rules to other AI tools...').start();

  const transformers: Record<keyof typeof EXPORT_TARGETS, (content: string) => string> = {
    windsurf: toWindsurf,
    aider: toAider,
    cline: toCline,
  };

  let exported = 0;

  for (const fmt of formats) {
    const target = EXPORT_TARGETS[fmt];
    const transformer = transformers[fmt];
    const outputPath = path.join(projectDir, target.file);
    const transformed = transformer(claudeContent);

    await fs.writeFile(outputPath, transformed, 'utf-8');
    exported++;
  }

  spinner.succeed('Export complete');
  console.log('');

  for (const fmt of formats) {
    const target = EXPORT_TARGETS[fmt];
    logSuccess(`${target.file} generated (${target.label})`);
  }

  console.log('');
  logInfo(
    `${exported} file${exported !== 1 ? 's' : ''} exported. These contain the same rules as your CLAUDE.md.`,
  );
}
