import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest';

/**
 * assembleTemplate reads real template files from TEMPLATES_DIR (resolved
 * relative to the compiled src/constants.ts at runtime). Because the tests
 * run against the TypeScript source directly via Vitest (not the compiled
 * output), TEMPLATES_DIR resolves correctly to the project root templates/
 * directory. We therefore use real templates for integration-style tests and
 * mock readFileSafe only for error-path tests.
 */

import { assembleTemplate, readTemplate } from '../../src/generator/assembler.js';
import { VERSION } from '../../src/constants.js';

describe('readTemplate', () => {
  it('throws when the template file does not exist', () => {
    expect(() => readTemplate('non-existent/fragment.md')).toThrow(
      'Template not found: non-existent/fragment.md',
    );
  });

  it('returns trimmed content for a known template', () => {
    const content = readTemplate('claude-md/base.md');
    expect(content.length).toBeGreaterThan(0);
    // Verify trimming — no leading/trailing whitespace
    expect(content).toBe(content.trim());
  });
});

describe('assembleTemplate', () => {
  describe('version comment', () => {
    it('inserts the version comment as the very first line', () => {
      const output = assembleTemplate('claude-md', ['base'], {
        projectName: 'test',
        techStack: 'Next.js',
        packageManager: 'npm',
        routerType: 'app',
        scripts: '- No scripts detected',
        framework: 'nextjs',
      });
      expect(output.startsWith('<!-- AI-KIT:START -->')).toBe(true);
      expect(output).toContain(`<!-- Generated by @horizontal/ai-kit v${VERSION} -->`);
      expect(output.endsWith('<!-- AI-KIT:END -->')).toBe(true);
    });
  });

  describe('fragment assembly', () => {
    it('assembles a single fragment without separator', () => {
      const output = assembleTemplate('claude-md', ['base'], {
        projectName: 'demo',
        techStack: '',
        packageManager: 'npm',
        routerType: 'app',
        scripts: '- No scripts detected',
        framework: 'unknown',
      });
      // Header content should appear
      expect(output).toContain('demo');
    });

    it('joins multiple fragments with --- separator', () => {
      const output = assembleTemplate('claude-md', ['base', 'typescript'], {
        projectName: 'demo',
        techStack: 'TypeScript',
        packageManager: 'npm',
        routerType: 'unknown',
        scripts: '- No scripts detected',
        framework: 'unknown',
      });
      // Multiple fragments are joined with \n\n---\n\n
      expect(output).toContain('\n\n---\n\n');
    });

    it('includes header before fragment body', () => {
      const output = assembleTemplate('claude-md', ['base'], {
        projectName: 'my-site',
        techStack: 'Next.js',
        packageManager: 'npm',
        routerType: 'app',
        scripts: '- No scripts detected',
        framework: 'nextjs',
      });
      const versionComment = `<!-- Generated by @horizontal/ai-kit v${VERSION} -->`;
      const versionIndex = output.indexOf(versionComment);
      const headerIndex = output.indexOf('my-site');
      expect(versionIndex).toBeLessThan(headerIndex);
    });

    it('throws when an unknown fragment is requested', () => {
      expect(() =>
        assembleTemplate('claude-md', ['does-not-exist'], {}),
      ).toThrow('Template not found: claude-md/does-not-exist.md');
    });
  });

  describe('placeholder replacement', () => {
    it('replaces {{projectName}} with the provided value', () => {
      const output = assembleTemplate('claude-md', ['base'], {
        projectName: 'replacement-test',
        techStack: '',
        packageManager: 'npm',
        routerType: 'unknown',
        scripts: '- No scripts detected',
        framework: 'unknown',
      });
      expect(output).toContain('replacement-test');
      expect(output).not.toContain('{{projectName}}');
    });

    it('replaces all occurrences of a placeholder', () => {
      const output = assembleTemplate('claude-md', ['base'], {
        projectName: 'multi-replace',
        techStack: '',
        packageManager: 'yarn',
        routerType: 'unknown',
        scripts: '- No scripts detected',
        framework: 'unknown',
      });
      // {{packageManager}} appears in the header template
      expect(output).not.toContain('{{packageManager}}');
      expect(output).toContain('yarn');
    });

    it('leaves unmatched placeholders in variables intact if not referenced in templates', () => {
      // Extra variables that do not correspond to any template placeholder are harmless
      const output = assembleTemplate('claude-md', ['base'], {
        projectName: 'safe-project',
        techStack: '',
        packageManager: 'npm',
        routerType: 'unknown',
        scripts: '- No scripts detected',
        framework: 'unknown',
        extraUnused: 'should-not-appear-literally-as-placeholder',
      });
      expect(output).not.toContain('{{extraUnused}}');
    });

    it('replaces {{scripts}} placeholder with provided scripts text', () => {
      const scripts = '- `npm run dev` → `next dev`\n- `npm run build` → `next build`';
      const output = assembleTemplate('claude-md', ['base'], {
        projectName: 'scripted',
        techStack: '',
        packageManager: 'npm',
        routerType: 'unknown',
        scripts,
        framework: 'unknown',
      });
      expect(output).toContain('next dev');
      expect(output).not.toContain('{{scripts}}');
    });
  });
});
