import path from 'path';
import fs from 'fs-extra';
import { TEMPLATES_DIR, VERSION } from '../constants.js';
import { readFileSafe } from '../utils.js';

export function readTemplate(relativePath: string): string {
  const fullPath = path.join(TEMPLATES_DIR, relativePath);
  const content = readFileSafe(fullPath);
  if (!content) {
    throw new Error(`Template not found: ${relativePath}`);
  }
  return content.trim();
}

export function loadCustomFragments(projectPath: string): string[] {
  const customDir = path.join(projectPath, '.ai-kit', 'fragments');
  if (!fs.existsSync(customDir)) return [];

  try {
    const files = fs.readdirSync(customDir).filter((f: string) => f.endsWith('.md'));
    return files.map((f: string) => {
      const content = fs.readFileSync(path.join(customDir, f), 'utf-8');
      return content.trim();
    }).filter(Boolean);
  } catch {
    return [];
  }
}

export function assembleTemplate(
  subfolder: 'claude-md' | 'cursorrules',
  fragments: string[],
  variables: Record<string, string>,
  options?: { customFragments?: string[]; strictness?: string },
): string {
  const versionComment = `<!-- Generated by ai-kit v${VERSION} -->`;
  const header = readTemplate('header.md');
  const body = fragments
    .map((name) => readTemplate(`${subfolder}/${name}.md`))
    .join('\n\n---\n\n');

  // Append strictness note
  const strictnessNote = options?.strictness && options.strictness !== 'standard'
    ? `\n\n---\n\n> **Strictness Level: ${options.strictness}**\n> ${getStrictnessDescription(options.strictness)}`
    : '';

  // Append custom fragments
  const customSection = options?.customFragments?.length
    ? '\n\n---\n\n' + options.customFragments.join('\n\n---\n\n')
    : '';

  const full = `${versionComment}\n${header}\n\n---\n\n${body}${strictnessNote}${customSection}`;
  const replaced = replacePlaceholders(full, variables);
  return `<!-- AI-KIT:START -->\n${replaced}\n<!-- AI-KIT:END -->`;
}

function getStrictnessDescription(level: string): string {
  switch (level) {
    case 'strict':
      return 'Enforce all rules strictly. No exceptions without explicit approval. All PRs must pass every check. Zero tolerance for `any` types, missing tests, or accessibility gaps.';
    case 'relaxed':
      return 'Rules are guidelines, not hard requirements. Prioritize shipping speed over perfection. Skip non-critical checks when under time pressure. Use best judgment.';
    default:
      return 'Standard enforcement. Follow rules by default, use judgment for edge cases.';
  }
}

export function replacePlaceholders(
  content: string,
  variables: Record<string, string>,
): string {
  let result = content;
  for (const [key, value] of Object.entries(variables)) {
    result = result.replaceAll(`{{${key}}}`, value);
  }
  return result;
}
