import path from 'path';
import { TEMPLATES_DIR, VERSION } from '../constants.js';
import { readFileSafe } from '../utils.js';

export function readTemplate(relativePath: string): string {
  const fullPath = path.join(TEMPLATES_DIR, relativePath);
  const content = readFileSafe(fullPath);
  if (!content) {
    throw new Error(`Template not found: ${relativePath}`);
  }
  return content.trim();
}

export function assembleTemplate(
  subfolder: 'claude-md' | 'cursorrules',
  fragments: string[],
  variables: Record<string, string>,
): string {
  const versionComment = `<!-- Generated by @horizontal/ai-kit v${VERSION} -->`;
  const header = readTemplate('header.md');
  const body = fragments
    .map((name) => readTemplate(`${subfolder}/${name}.md`))
    .join('\n\n---\n\n');

  const full = `${versionComment}\n${header}\n\n---\n\n${body}`;
  const replaced = replacePlaceholders(full, variables);
  return `<!-- AI-KIT:START -->\n${replaced}\n<!-- AI-KIT:END -->`;
}

export function replacePlaceholders(
  content: string,
  variables: Record<string, string>,
): string {
  let result = content;
  for (const [key, value] of Object.entries(variables)) {
    result = result.replaceAll(`{{${key}}}`, value);
  }
  return result;
}
