import type { ProjectScan } from '../types.js';
import { selectFragments } from './claude-md.js';
import { readTemplate, replacePlaceholders } from './assembler.js';
import { buildCursorVariables } from './cursorrules.js';
import { VERSION } from '../constants.js';

export interface MdcFile {
  filename: string;
  content: string;
}

const MDC_CONFIG: Record<string, { description: string; globs: string }> = {
  base: {
    description: 'Project coding standards and conventions',
    globs: '**/*',
  },
  'nextjs-app-router': {
    description: 'Next.js App Router patterns and best practices',
    globs: 'app/**/*.{ts,tsx}, src/app/**/*.{ts,tsx}',
  },
  'nextjs-pages-router': {
    description: 'Next.js Pages Router patterns and best practices',
    globs: 'pages/**/*.{ts,tsx}, src/pages/**/*.{ts,tsx}',
  },
  'sitecore-xmc': {
    description: 'Sitecore XM Cloud component patterns and field helpers',
    globs: 'src/components/**/*.{ts,tsx}',
  },
  'optimizely-saas': {
    description: 'Optimizely SaaS CMS patterns, Visual Builder, and Graph API',
    globs: 'src/components/**/*.{ts,tsx}, src/gql/**/*.{ts,graphql}',
  },
  tailwind: {
    description: 'Tailwind CSS conventions and utility patterns',
    globs: '**/*.{tsx,jsx,css}',
  },
  typescript: {
    description: 'TypeScript strict typing conventions',
    globs: '**/*.{ts,tsx}',
  },
  monorepo: {
    description: 'Monorepo workspace conventions',
    globs: '**/*',
  },
  figma: {
    description: 'Figma-to-code workflow and design token rules',
    globs: 'src/components/**/*.{ts,tsx}, tokens/**/*',
  },
  'static-site': {
    description: 'Static site generation (SSG/ISR) rules and patterns',
    globs: 'app/**/*.{ts,tsx}, src/app/**/*.{ts,tsx}, next.config.*',
  },
};

export function generateMdcFiles(scan: ProjectScan): MdcFile[] {
  const fragments = selectFragments(scan);
  const variables = buildCursorVariables(scan);

  return fragments.map((fragment) => {
    const config = MDC_CONFIG[fragment] || {
      description: fragment,
      globs: '**/*',
    };
    const body = readTemplate(`cursorrules/${fragment}.md`);
    const replaced = replacePlaceholders(body, variables);

    const frontmatter = [
      '---',
      `description: ${config.description}`,
      `globs: ${config.globs}`,
      'alwaysApply: true',
      '---',
    ].join('\n');

    return {
      filename: `${fragment}.mdc`,
      content: `${frontmatter}\n\n<!-- Generated by ai-kit v${VERSION} -->\n\n${replaced}`,
    };
  });
}
